# Example 1
#
# Single box with some custom configuration.

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "trusty64"
  config.vm.network :private_network, ip: "192.168.0.42"
end
