# Example 1
#
# Single box with some custom configuration.
#
# NOTE: Make sure you have the trusty64 base box installed...
# vagrant box add trusty http://files.vagrantup.com/trusty64.box


Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "trusty64"
  config.vm.network :private_network, ip: "192.168.0.42"
end
